<?php
/**
 * @file
 * Stanford Jumpstart Engineering for Department Sites
 *
 * @author  Caryl Westerberg <cjwest@stanford.edu>
 * Provides custom functionality for School of Engineering departments sites.
 *
 */




/**
 * Implements hook_form_alter().
 */
function stanford_jse_dept_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == "system_theme_settings" || $form_id == "stanford_jumpstart_homepage_dashboard_form") {
    dpm($form);

    drupal_add_css(drupal_get_path('module', 'stanford_jumpstart_home_dept')
      . '/css/stanford_jumpstart_home_dept.css');

    //Add SoE Styles
    $form['design_container']['styles']['#options']['styles-soe'] =
      '<span class="design-style ds-soe">' . t('SoE') . '</span>';

    //Add SoE font variables
    $form['design_container']['fonts']['#options']['fonts-slab-soe'] =
      '<span class="design-font df-slab">' . t('SoE Slab') . '</span>';
  }
}

/**
 * @param $css
 * Set the SoE styles.
 * See stanford_framework_css_alter()
 */
function stanford_jse_dept_css_alter(&$css) {

  $styles = theme_get_setting('styles');

  // Styles variables.
  switch ($styles) {
    case "styles-soe":
      drupal_add_css(drupal_get_path('module', 'stanford_soe_helper') . '/css/soe_helper.css', array(
        'group' => CSS_THEME,
        'media' => 'all',
        'weight' => 100,
        'preprocess' => TRUE
      ));
      break;
    default:
  }


  // SoE fonts variables
  switch ($fonts) {
    case "fonts-sans":
      drupal_add_css(drupal_get_path('module', 'stanford_soe_helper') . '/css/soe_helper.css', array(
        'group' => CSS_THEME,
        'media' => 'all',
        'weight' => 98,
        'preprocess' => TRUE
      ));
      break;
    default:
  }
}