<?php
/**
 * @file
 * File description
 *
 * Long description
 */

/**
 * Implements hook_form_alter().
 */
function stanford_jumpstart_engineering_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "system_theme_settings" || $form_id == "stanford_jumpstart_homepage_dashboard_form") {

    // Remove unneeded styles
    unset($form['design_container']['styles']['#options']['styles-dark']);
    unset($form['design_container']['styles']['#options']['styles-bright']);
    unset($form['design_container']['styles']['#options']['styles-vivid']);
  }

}

/**
 * Implements hook_form_FORM_ID_alter() for stanford_news_item_node_form.
 */
function stanford_jumpstart_engineering_form_stanford_news_item_node_form_alter(
  &$form,
  &$form_state,
  $form_id) {

  // Handle deprecation of image credits.
  if (function_exists('stanford_news_extras_deprecate_image_credits')) {
    stanford_news_extras_deprecate_image_credits($form, $form_id);
  }
}

