<?php
/**
 * @file
 * File description
 *
 * Long description
 */

/**
 * Implements hook_form_alter().
 */
function stanford_jumpstart_engineering_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "system_theme_settings" || $form_id == "stanford_jumpstart_homepage_dashboard_form") {

    $theme = variable_get("theme_default", "stanford_framework");
    $style = theme_get_setting('styles', $theme);

    $form['design_container']['styles'] = array(
      '#type'          => 'radios',
      '#title'         => t('Choose styles'),
      '#default_value' => $style,
      '#options'       => array(
        'styles-light' => "<span class=\"design-style ds-light\">" . t('Light') . "</span>",
        //'styles-dark' => "<span class=\"design-style ds-dark\">" . t('Dark') . "</span>",
        'styles-plain' => "<span class=\"design-style ds-plain\">" . t('Plain') . "</span>",
        'styles-rich' => "<span class=\"design-style ds-rich\">" . t('Rich') . "</span>",
        //'styles-bright' => "<span class=\"design-style ds-bright\">" . t('Bright') . "</span>",
        'styles-contrast' => "<span class=\"design-style ds-high\">" . t('High Contrast') . "</span>",
        'styles-cardinal' => "<span class=\"design-style ds-cardinal\">" . t('Cardinal') . "</span>",
      ),
    );
  }

}
/**
 * Implements preprocess_page().
 */
function stanford_jumpstart_engineering_preprocess_page(&$vars) {

  if (!path_is_admin(current_path())) {

    $file_path = drupal_get_path('module', 'stanford_jumpstart_engineering') . '/css/stanford_jumpstart_engineering.css';

    // CSS Injector file weights start at 200.
    // See http://www.rit.edu/drupal/api/drupal/sites!all!modules!css_injector!css_injector.module/7.43.
    $weight = 180;
    $conditions = "admin
admin*
admin/*
block/*/edit*
block/add*
block/*/delete
node/*/edit
node/add*
node/*/delete
user/*/edit";

    $css_rules = array();
    $css_rules['rule_conditions'] = $conditions;
    $css_rules['rule_type'] = CSS_INJECTOR_PAGES_NOTLISTED;

    $pass = _css_injector_evaluate_rule($css_rules);
    if ($pass) {

      drupal_add_css($file_path, array(
        'type' => 'file',
        'group' => CSS_THEME,
        'media' => "all",
        'preprocess' => TRUE,
        'weight' => $weight
      ));
    }
  }
}
